/*****************************************************************************
*
* Copyright (c) 2000 - 2015, Lawrence Livermore National Security, LLC
* Produced at the Lawrence Livermore National Laboratory
* LLNL-CODE-442911
* All rights reserved.
*
* This file is  part of VisIt. For  details, see https://visit.llnl.gov/.  The
* full copyright notice is contained in the file COPYRIGHT located at the root
* of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
*
* Redistribution  and  use  in  source  and  binary  forms,  with  or  without
* modification, are permitted provided that the following conditions are met:
*
*  - Redistributions of  source code must  retain the above  copyright notice,
*    this list of conditions and the disclaimer below.
*  - Redistributions in binary form must reproduce the above copyright notice,
*    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
*    documentation and/or other materials provided with the distribution.
*  - Neither the name of  the LLNS/LLNL nor the names of  its contributors may
*    be used to endorse or promote products derived from this software without
*    specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
* ARE  DISCLAIMED. IN  NO EVENT  SHALL LAWRENCE  LIVERMORE NATIONAL  SECURITY,
* LLC, THE  U.S.  DEPARTMENT OF  ENERGY  OR  CONTRIBUTORS BE  LIABLE  FOR  ANY
* DIRECT,  INDIRECT,   INCIDENTAL,   SPECIAL,   EXEMPLARY,  OR   CONSEQUENTIAL
* DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
* SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
* CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
* LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
* OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
* DAMAGE.
*
*****************************************************************************/

// ************************************************************************* //
//                             avtGraviTPlot.C                                 //
// ************************************************************************* //

#include <avtGraviTPlot.h>

#include <avtGraviTFilter.h>

// GRAVIT includes

#include <apps/render/RenderAPI.h>
#include <View3DAttributes.h>
#include <WindowAttributes.h>
#include <avtDatabase.h>
#include <avtCallback.h>
#include <avtDatabaseMetaData.h>
#include <vtkCellData.h>
#include <vtkDataSet.h>
#include <vtkPointSet.h>
#include <vtkImageData.h>
#include <vtkPolyData.h>
#include <vtkCellArray.h>
#include <vtkSmartPointer.h>
struct GravitProgramConfig
{
    // Camera Params
    double eyePoint[3];
    double focalPoint[3];
    double upVector[3];
    double view_direction[3];
    int filmSize[2];

    //Tracing Parms
    int maxDepth;
    int samples;
    unsigned char backgroundColor[3];
};


GravitProgramConfig hackyConfig;
avtDataObject_p hackyInput;



// ****************************************************************************
//  Method: avtGraviTPlot constructor
//
//  Programmer: applekey -- generated by xml2avt
//  Creation:   Thu Apr 14 09:20:02 PDT 2016
//
// ****************************************************************************
class avtGraviTRenderer : public avtCustomRenderer
{
 virtual void Render(vtkDataSet * ds){std::cerr<<"Render"<<std::endl;}; 
};
avtGraviTPlot::avtGraviTPlot()
{
    char * abc;
    //Draw(abc);


    GraviTFilter = new avtGraviTFilter();
    ref_ptr<avtGraviTRenderer> renderer =  new avtGraviTRenderer;

    avtCustomRenderer_p cr;
    CopyTo(cr, renderer);
    mapper = new avtUserDefinedMapper(cr);
}


// ****************************************************************************
//  Method: avtGraviTPlot destructor
//
//  Programmer: applekey -- generated by xml2avt
//  Creation:   Thu Apr 14 09:20:02 PDT 2016
//
// ****************************************************************************

avtGraviTPlot::~avtGraviTPlot()
{
    if (mapper != NULL)
    {
        delete mapper;
        mapper = NULL;
    }
    if (GraviTFilter != NULL)
    {
        delete GraviTFilter;
        GraviTFilter = NULL;
    }
}


// ****************************************************************************
//  Method:  avtGraviTPlot::Create
//
//  Purpose:
//    Call the constructor.
//
//  Programmer: applekey -- generated by xml2avt
//  Creation:   Thu Apr 14 09:20:02 PDT 2016
//
// ****************************************************************************

avtPlot*
avtGraviTPlot::Create()
{
    return new avtGraviTPlot;
}


// ****************************************************************************
//  Method: avtGraviTPlot::GetMapper
//
//  Purpose:
//      Gets a mapper for this plot, it is actually a variable mapper.
//
//  Returns:    The variable mapper typed as its base class mapper.
//
//  Programmer: applekey -- generated by xml2avt
//  Creation:   Thu Apr 14 09:20:02 PDT 2016
//
// ****************************************************************************

avtMapper *
avtGraviTPlot::GetMapper(void)
{
    return mapper;
}


// ****************************************************************************
//  Method: avtGraviTPlot::ApplyOperators
//
//  Purpose:
//      Applies the operators associated with a GraviT plot.  
//      The output from this method is a query-able object.
//
//  Arguments:
//      input   The input data object.
//
//  Returns:    The data object after the GraviT plot has been applied.
//
//  Programmer: applekey -- generated by xml2avt
//  Creation:   Thu Apr 14 09:20:02 PDT 2016
//
// ****************************************************************************

avtDataObject_p
avtGraviTPlot::ApplyOperators(avtDataObject_p input)
{
    GraviTFilter->SetInput(input);
    return GraviTFilter->GetOutput();
}


// ****************************************************************************
//  Method: avtGraviTPlot::ApplyRenderingTransformation
//
//  Purpose:
//      Applies the rendering transformation associated with a GraviT plot.  
//
//  Arguments:
//      input   The input data object.
//
//  Returns:    The data object after the GraviT plot has been applied.
//
//  Programmer: applekey -- generated by xml2avt
//  Creation:   Thu Apr 14 09:20:02 PDT 2016
//
// ****************************************************************************

avtDataObject_p
avtGraviTPlot::ApplyRenderingTransformation(avtDataObject_p input)
{
//input is the data to render
    //GraviTFilter->SetInput(input);
    //return GraviTFilter->GetOutput();
    hackyInput = input;
    return input;
}


// ****************************************************************************
//  Method: avtGraviTPlot::CustomizeBehavior
//
//  Purpose:
//      Customizes the behavior as appropriate for a GraviT plot.  This includes
//      behavior like shifting towards or away from the screen.
//
//  Programmer: applekey -- generated by xml2avt
//  Creation:   Thu Apr 14 09:20:02 PDT 2016
//
// ****************************************************************************

void
avtGraviTPlot::CustomizeBehavior(void)
{
    //behavior->SetShiftFactor(0.6);
}


// ****************************************************************************
//  Method: avtGraviTPlot::CustomizeMapper
//
//  Purpose:
//      A hook from the base class that allows the plot to change its mapper
//      based on the dataset input. 
//
//  Arguments:
//      doi     The data object information.
//
//  Programmer: applekey -- generated by xml2avt
//  Creation:   Thu Apr 14 09:20:02 PDT 2016
//
// ****************************************************************************

void
avtGraviTPlot::CustomizeMapper(avtDataObjectInformation &doi)
{
/* Example of usage.
    int dim = doi.GetAttributes().GetCurrentSpatialDimension();
    if (dim == 2)
    {
    }
    else
    {
    }
 */
}
avtImage_p
avtGraviTPlot::ImageExecute(avtImage_p input,
const WindowAttributes &window_atts)
{
//window attr has data about cam

    std::cerr<<"In Image Execute"<<std::endl;
    char * abc;
    VisitAdapter adapter;
    

    // Get Visit view attributes
    int size[2];
    input->GetSize(size,size+1);

    hackyConfig.filmSize[0] = size[0];
    hackyConfig.filmSize[1] = size[1];

    View3DAttributes viewAttr= window_atts.GetView3D();



    // double * viewNormal = viewAttr.GetViewNormal();
    // double * focalPoint = viewAttr.GetViewNormal();
    // double zoom = viewAttr.GetImageZoom();
    // double fov = viewAttr.GetEyeAngle(); // not owkring



    //-0.01680081151425838 0.1101529560983181 -0.001482265070080757 focal point
    //30 angle
    //0 0 1 view normal

    double fov = 30;
    double upVector[3] = {0,1.0,0};
    double focalPoint[3] = {0,0,0};
    double viewNormal[3] = {0, 0, 1};
    double zoom = 1.0;


    adapter.SetCamera(focalPoint, upVector, viewNormal, zoom, fov);

    // check out the data
    // const avtDataAttributes &datts = input->GetInfo().GetAttributes();
    // std::string db = input->GetInfo().GetAttributes().GetFullDBName();

    //debug5<<"datts->GetTime(): "<<datts.GetTime()<<endl;
    //debug5<<"datts->GetTimeIndex(): "<<datts.GetTimeIndex()<<endl;
    //debug5<<"datts->GetCycle(): "<<datts.GetCycle()<<endl;

    //ref_ptr<avtDatabase> dbp = avtCallback::GetDatabase(db, datts.GetTimeIndex(), NULL);
    //avtDatabaseMetaData *md = dbp->GetMetaData(datts.GetTimeIndex(), 1);
    //std::string mesh = md->MeshForVar(datts.GetVariableName());
    //const avtMeshMetaData *mmd = md->GetMesh(mesh);


    avtDataset *ds = (avtDataset *) *hackyInput;
    vtkDataSet *ds2 = ds->dataTree->GetSingleLeaf();

    vtkCellData * cellData = ds2->GetCellData();
    // int isA = ds2->IsA("vtkPolyData");
    // int isB = ds2->IsA("vtkPointSet");
    // std::cerr<<isA<<" "<<isB<<std::endl;
    vtkPolyData * contourPD = (vtkPolyData *) ds2;
    int numPoints = contourPD->GetNumberOfPoints();
    vtkCellArray * contourFaces = contourPD->GetPolys();
    // get the verts
    int contourSize = contourPD->GetNumberOfPoints();  
    
    double * points = new double[contourSize *3];


    for(vtkIdType i = 0; i < contourSize; i++)  
    {  
            double vtkPts[3] = {0.0,0.0,0.0};  
            contourPD->GetPoints()->GetPoint(i,vtkPts); 

            points[i*3] = vtkPts[0];
            points[i*3 +1] = vtkPts[1];
            points[i*3 + 2] = vtkPts[2];

            //std::cout<<vtkPts[0]<<" "<<vtkPts[1]<<" "<<vtkPts[2]<<std::endl;
            //glm::vec3 currentPoint = glm::vec3(vtkPts[0], vtkPts[1], vtkPts[2]);  
            //mesh->addVertex(currentPoint);  
    }  

    // link the edge

    vtkSmartPointer<vtkIdList> idList = vtkSmartPointer<vtkIdList>::New();
    contourFaces->InitTraversal();  

    int totalEdges = contourFaces->GetNumberOfCells();
    int * edges = new int[totalEdges * 3];

    for(int i = 0; i < totalEdges; i++)  
    {  
            contourFaces->GetNextCell(idList);  
            int v1 = idList->GetId(0)+1;  
            int v2 = idList->GetId(1)+1;  
            int v3 = idList->GetId(2)+1;  

            edges[i*3] = v1;
            edges[i*3 + 1] = v2;
            edges[i*3 + 2] = v3;
           
            //std::cerr<<v1<<" "<<v2<<" "<<v3<<" "<<std::endl;
            //mesh->addFace(v1,v2,v3);  
    } 

    double materialProp[3] ={0.5,0.5,0.5}; 
    adapter.DrawTri(points, contourSize, edges, totalEdges,0, materialProp);

    delete [] edges;
    delete [] points;

    unsigned char * data =input->GetImage().GetRGBBuffer();
    for(int i = 0;i< 30000;i++)
    {
      data[3*i] = (unsigned char) 255;
    }
    std::cerr<<size[0]<<" "<<size[1]<<std::endl;
    avtImage_p rv = input;

    return rv;
}


// ****************************************************************************
//  Method: avtGraviTPlot::SetAtts
//
//  Purpose:
//      Sets the atts for the GraviT plot.
//
//  Arguments:
//      atts    The attributes for this GraviT plot.
//
//  Programmer: applekey -- generated by xml2avt
//  Creation:   Thu Apr 14 09:20:02 PDT 2016
//
// ****************************************************************************

void
avtGraviTPlot::SetAtts(const AttributeGroup *a)
{
    //const GraviTAttributes *newAtts = (const GraviTAttributes *)a;
}
