/*****************************************************************************
*
* Copyright (c) 2000 - 2015, Lawrence Livermore National Security, LLC
* Produced at the Lawrence Livermore National Laboratory
* LLNL-CODE-442911
* All rights reserved.
*
* This file is  part of VisIt. For  details, see https://visit.llnl.gov/.  The
* full copyright notice is contained in the file COPYRIGHT located at the root
* of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
*
* Redistribution  and  use  in  source  and  binary  forms,  with  or  without
* modification, are permitted provided that the following conditions are met:
*
*  - Redistributions of  source code must  retain the above  copyright notice,
*    this list of conditions and the disclaimer below.
*  - Redistributions in binary form must reproduce the above copyright notice,
*    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
*    documentation and/or other materials provided with the distribution.
*  - Neither the name of  the LLNS/LLNL nor the names of  its contributors may
*    be used to endorse or promote products derived from this software without
*    specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
* ARE  DISCLAIMED. IN  NO EVENT  SHALL LAWRENCE  LIVERMORE NATIONAL  SECURITY,
* LLC, THE  U.S.  DEPARTMENT OF  ENERGY  OR  CONTRIBUTORS BE  LIABLE  FOR  ANY
* DIRECT,  INDIRECT,   INCIDENTAL,   SPECIAL,   EXEMPLARY,  OR   CONSEQUENTIAL
* DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
* SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
* CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
* LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
* OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
* DAMAGE.
*
*****************************************************************************/

// ************************************************************************* //
//                             avtGraviTPlot.C                                 //
// ************************************************************************* //

#include <avtGraviTPlot.h>

#include <avtGraviTFilter.h>


// ****************************************************************************
//  Method: avtGraviTPlot constructor
//
//  Programmer: applekey -- generated by xml2avt
//  Creation:   Thu Apr 14 09:20:02 PDT 2016
//
// ****************************************************************************

avtGraviTPlot::avtGraviTPlot()
{
    GraviTFilter = new avtGraviTFilter(ARGS FOR FILTER);
    myMapper   = ....;
}


// ****************************************************************************
//  Method: avtGraviTPlot destructor
//
//  Programmer: applekey -- generated by xml2avt
//  Creation:   Thu Apr 14 09:20:02 PDT 2016
//
// ****************************************************************************

avtGraviTPlot::~avtGraviTPlot()
{
    if (myMapper != NULL)
    {
        delete myMapper;
        myMapper = NULL;
    }
    if (GraviTFilter != NULL)
    {
        delete GraviTFilter;
        GraviTFilter = NULL;
    }
}


// ****************************************************************************
//  Method:  avtGraviTPlot::Create
//
//  Purpose:
//    Call the constructor.
//
//  Programmer: applekey -- generated by xml2avt
//  Creation:   Thu Apr 14 09:20:02 PDT 2016
//
// ****************************************************************************

avtPlot*
avtGraviTPlot::Create()
{
    return new avtGraviTPlot;
}


// ****************************************************************************
//  Method: avtGraviTPlot::GetMapper
//
//  Purpose:
//      Gets a mapper for this plot, it is actually a variable mapper.
//
//  Returns:    The variable mapper typed as its base class mapper.
//
//  Programmer: applekey -- generated by xml2avt
//  Creation:   Thu Apr 14 09:20:02 PDT 2016
//
// ****************************************************************************

avtMapper *
avtGraviTPlot::GetMapper(void)
{
    return myMapper;
}


// ****************************************************************************
//  Method: avtGraviTPlot::ApplyOperators
//
//  Purpose:
//      Applies the operators associated with a GraviT plot.  
//      The output from this method is a query-able object.
//
//  Arguments:
//      input   The input data object.
//
//  Returns:    The data object after the GraviT plot has been applied.
//
//  Programmer: applekey -- generated by xml2avt
//  Creation:   Thu Apr 14 09:20:02 PDT 2016
//
// ****************************************************************************

avtDataObject_p
avtGraviTPlot::ApplyOperators(avtDataObject_p input)
{
    GraviTFilter->SetInput(input);
    return GraviTFilter->GetOutput();
}


// ****************************************************************************
//  Method: avtGraviTPlot::ApplyRenderingTransformation
//
//  Purpose:
//      Applies the rendering transformation associated with a GraviT plot.  
//
//  Arguments:
//      input   The input data object.
//
//  Returns:    The data object after the GraviT plot has been applied.
//
//  Programmer: applekey -- generated by xml2avt
//  Creation:   Thu Apr 14 09:20:02 PDT 2016
//
// ****************************************************************************

avtDataObject_p
avtGraviTPlot::ApplyRenderingTransformation(avtDataObject_p input)
{
    GraviTFilter->SetInput(input);
    return GraviTFilter->GetOutput();
}


// ****************************************************************************
//  Method: avtGraviTPlot::CustomizeBehavior
//
//  Purpose:
//      Customizes the behavior as appropriate for a GraviT plot.  This includes
//      behavior like shifting towards or away from the screen.
//
//  Programmer: applekey -- generated by xml2avt
//  Creation:   Thu Apr 14 09:20:02 PDT 2016
//
// ****************************************************************************

void
avtGraviTPlot::CustomizeBehavior(void)
{
    //behavior->SetShiftFactor(0.6);
}


// ****************************************************************************
//  Method: avtGraviTPlot::CustomizeMapper
//
//  Purpose:
//      A hook from the base class that allows the plot to change its mapper
//      based on the dataset input. 
//
//  Arguments:
//      doi     The data object information.
//
//  Programmer: applekey -- generated by xml2avt
//  Creation:   Thu Apr 14 09:20:02 PDT 2016
//
// ****************************************************************************

void
avtGraviTPlot::CustomizeMapper(avtDataObjectInformation &doi)
{
/* Example of usage.
    int dim = doi.GetAttributes().GetCurrentSpatialDimension();
    if (dim == 2)
    {
    }
    else
    {
    }
 */
}


// ****************************************************************************
//  Method: avtGraviTPlot::SetAtts
//
//  Purpose:
//      Sets the atts for the GraviT plot.
//
//  Arguments:
//      atts    The attributes for this GraviT plot.
//
//  Programmer: applekey -- generated by xml2avt
//  Creation:   Thu Apr 14 09:20:02 PDT 2016
//
// ****************************************************************************

void
avtGraviTPlot::SetAtts(const AttributeGroup *a)
{
    const GraviTAttributes *newAtts = (const GraviTAttributes *)a;

    BASED ON ATTRIBUTE VALUES, CHANGE PARAMETERS IN MAPPER AND FILTER.
}
