/*****************************************************************************
*
* Copyright (c) 2000 - 2015, Lawrence Livermore National Security, LLC
* Produced at the Lawrence Livermore National Laboratory
* LLNL-CODE-442911
* All rights reserved.
*
* This file is  part of VisIt. For  details, see https://visit.llnl.gov/.  The
* full copyright notice is contained in the file COPYRIGHT located at the root
* of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
*
* Redistribution  and  use  in  source  and  binary  forms,  with  or  without
* modification, are permitted provided that the following conditions are met:
*
*  - Redistributions of  source code must  retain the above  copyright notice,
*    this list of conditions and the disclaimer below.
*  - Redistributions in binary form must reproduce the above copyright notice,
*    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
*    documentation and/or other materials provided with the distribution.
*  - Neither the name of  the LLNS/LLNL nor the names of  its contributors may
*    be used to endorse or promote products derived from this software without
*    specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
* ARE  DISCLAIMED. IN  NO EVENT  SHALL LAWRENCE  LIVERMORE NATIONAL  SECURITY,
* LLC, THE  U.S.  DEPARTMENT OF  ENERGY  OR  CONTRIBUTORS BE  LIABLE  FOR  ANY
* DIRECT,  INDIRECT,   INCIDENTAL,   SPECIAL,   EXEMPLARY,  OR   CONSEQUENTIAL
* DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
* SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
* CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
* LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
* OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
* DAMAGE.
*
*****************************************************************************/

// ************************************************************************* //
//                              avtGraviTFilter.h                              //
// ************************************************************************* //

#ifndef AVT_GraviT_FILTER_H
#define AVT_GraviT_FILTER_H


#include <avtDataTreeIterator.h>
#include <avtDatasetOnDemandFilter.h>

int avtGraviTFilter_LoadDomain(void*);

// ****************************************************************************
//  Class: avtGraviTFilter
//
//  Purpose:
//      This operator is the implied operator associated with an GraviT plot.
//
//  Programmer: applekey -- generated by xml2avt
//  Creation:   Thu Apr 14 09:20:02 PDT 2016
//
// ****************************************************************************


class avtGraviTFilter :  
    virtual public avtDatasetOnDemandFilter
   ,virtual public avtDatasetToDatasetFilter
{
    friend int avtGraviTFilter_LoadDomain(void*);
  public:
                              avtGraviTFilter();
    virtual                  ~avtGraviTFilter();

    virtual const char       *GetType(void)   { return "avtGraviTFilter"; };
    virtual const char       *GetDescription(void)
                                  { return "Performing GraviT"; };

    virtual int             LoadDomain(int domainId, double ** points, int& numPoints, int ** edges, int& numEdges);

    virtual void             LoadBoundingBoxes(int & numBoundingBox, double ** lower, double ** upper);

    vtkDataSet * hackyDS;

  protected:
    virtual void               Execute(){};
    virtual void                 PurgeDomain( const int domain, const int timeStep ) {};
    virtual avtDataRepresentation *ExecuteData(avtDataRepresentation *);
    virtual void              UpdateDataObjectInfo(void);
};


#endif
