/*****************************************************************************
*
* Copyright (c) 2000 - 2015, Lawrence Livermore National Security, LLC
* Produced at the Lawrence Livermore National Laboratory
* LLNL-CODE-442911
* All rights reserved.
*
* This file is  part of VisIt. For  details, see https://visit.llnl.gov/.  The
* full copyright notice is contained in the file COPYRIGHT located at the root
* of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
*
* Redistribution  and  use  in  source  and  binary  forms,  with  or  without
* modification, are permitted provided that the following conditions are met:
*
*  - Redistributions of  source code must  retain the above  copyright notice,
*    this list of conditions and the disclaimer below.
*  - Redistributions in binary form must reproduce the above copyright notice,
*    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
*    documentation and/or other materials provided with the distribution.
*  - Neither the name of  the LLNS/LLNL nor the names of  its contributors may
*    be used to endorse or promote products derived from this software without
*    specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
* ARE  DISCLAIMED. IN  NO EVENT  SHALL LAWRENCE  LIVERMORE NATIONAL  SECURITY,
* LLC, THE  U.S.  DEPARTMENT OF  ENERGY  OR  CONTRIBUTORS BE  LIABLE  FOR  ANY
* DIRECT,  INDIRECT,   INCIDENTAL,   SPECIAL,   EXEMPLARY,  OR   CONSEQUENTIAL
* DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
* SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
* CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
* LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
* OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
* DAMAGE.
*
*****************************************************************************/

// ************************************************************************* //
//                              avtGraviTFilter.C                              //
// ************************************************************************* //

#include <avtGraviTFilter.h>

// remove these refs later
#include <vtkDataSet.h>
#include <vtkPolyData.h>
#include <vtkSmartPointer.h>
#include <vtkCellArray.h>
#include <float.h>
#include <avtIntervalTree.h>
#include <avtMetaData.h>

// ****************************************************************************
//  Method: avtGraviTFilter constructor
//
//  Programmer: applekey -- generated by xml2avt
//  Creation:   Thu Apr 14 09:20:02 PDT 2016
//
// ****************************************************************************

avtGraviTFilter::avtGraviTFilter()
{
}


// ****************************************************************************
//  Method: avtGraviTFilter destructor
//
//  Programmer: applekey -- generated by xml2avt
//  Creation:   Thu Apr 14 09:20:02 PDT 2016
//
// ****************************************************************************

avtGraviTFilter::~avtGraviTFilter()
{
}

bool avtGraviTFilter::HasExtents()
{
    avtIntervalTree * tree = GetMetaData()->GetSpatialExtents();
    return (tree!= NULL? true:false);
}

void avtGraviTFilter::LoadBoundingBoxes(int & numBoundingBox, double ** lower, double ** upper)
{
    avtIntervalTree * tree = GetMetaData()->GetSpatialExtents();
    numBoundingBox = tree->GetNLeaves();

    //std::cerr<<"NumBoundingBox"<<numBoundingBox<<std::endl;

    *lower = new double[numBoundingBox * 3];
    *upper = new double[numBoundingBox * 3];

    double * lowerPtr = *lower;
    double * upperPtr = *upper;

    for(int i = 0;i<numBoundingBox;i++)
    {   
        double bBox[6];
        tree->GetLeafExtents(i, bBox);

        lowerPtr[0] = bBox[0];
        lowerPtr[1] = bBox[2];
        lowerPtr[2] = bBox[4];

        upperPtr[0] = bBox[1];
        upperPtr[1] = bBox[3];
        upperPtr[2] = bBox[5];
        //std::cerr<<"bBox:"<<bBox[0]<<":"<<bBox[1]<<":"<<bBox[2]<<":"<<bBox[3]<<":"<<bBox[4]<<":"<<bBox[5]<<std::endl;

        lowerPtr += 3;
        upperPtr += 3;
    }
}


int avtGraviTFilter::LoadDomain(int domainId, double ** ppoints, int& numPoints, int ** pedges, int& numEdges)
{
    std::cerr<<"Loading Domain Id: "<<domainId<<std::endl;

    vtkDataSet *ds2 = GetDomain(domainId ,0);

    //std::cerr<<"Got Domain Data"<<std::endl;
    
    vtkCellData * cellData = ds2->GetCellData();
    vtkPolyData * contourPD = (vtkPolyData *) ds2;
    numPoints = contourPD->GetNumberOfPoints();
    vtkCellArray * contourFaces = contourPD->GetPolys();
    // get the verts
    int contourSize = contourPD->GetNumberOfPoints();  
    
    *ppoints = new double[contourSize *3];

    double * points =  *ppoints;

    for(vtkIdType i = 0; i < contourSize; i++)  
    {  
            double vtkPts[3] = {0.0,0.0,0.0};  
            contourPD->GetPoints()->GetPoint(i,vtkPts); 

            points[i*3] = vtkPts[0];
            points[i*3 +1] = vtkPts[1];
            points[i*3 + 2] = vtkPts[2];
    }  

    // link the edge

    vtkSmartPointer<vtkIdList> idList = vtkSmartPointer<vtkIdList>::New();
    contourFaces->InitTraversal();  

    int totalEdges = contourFaces->GetNumberOfCells();
    numEdges = totalEdges;
    *pedges = new int[totalEdges * 3];
    int * edges=  *pedges;

    for(int i = 0; i < totalEdges; i++)  
    {  
        contourFaces->GetNextCell(idList);  
        int v1 = idList->GetId(0)+1;  
        int v2 = idList->GetId(1)+1;  
        int v3 = idList->GetId(2)+1;  

        edges[i*3] = v1;
        edges[i*3 + 1] = v2;
        edges[i*3 + 2] = v3;
    }
    //std::cerr<<"numverts"<<numPoints<<"numEdges"<<numEdges<<std::endl;


    //std::cerr<<"Callback func success"<<std::endl;

	return 0;
}



// ****************************************************************************
//  Method: avtGraviTFilter::ExecuteData
//
//  Purpose:
//      Sends the specified input and output through the GraviT filter.
//
//  Arguments:
//      in_dr     The input data representation.
//
//  Returns:      The output data representation.
//
//  Programmer: applekey -- generated by xml2avt
//  Creation:   Thu Apr 14 09:20:02 PDT 2016
//
// ****************************************************************************

avtDataRepresentation *
avtGraviTFilter::ExecuteData(avtDataRepresentation *in_dr)
{
    //
    // Get the VTK data set, the domain number, and the label.
    //
   // vtkDataSet *in_ds = in_dr->GetDataVTK();
    //int domain = in_dr->GetDomain();
    //std::string label = in_dr->GetLabel();
    return in_dr;
    
}


// ****************************************************************************
//  Method: avtGraviTFilter::UpdateDataObjectInfo
//
//  Purpose:
//      Allows the filter to change its output's data object information, which
//      is a description of the data object.
//
//  Programmer: applekey -- generated by xml2avt
//  Creation:   Thu Apr 14 09:20:02 PDT 2016
//
// ****************************************************************************

void
avtGraviTFilter::UpdateDataObjectInfo(void)
{
    std::cerr<<"In Gravit Filter, hasExtents"<<HasExtents()<<std::endl;
    SetOperatingOnDemand(HasExtents());
}
