// ***************************************************************************
//
// Copyright (c) 2000 - 2015, Lawrence Livermore National Security, LLC
// Produced at the Lawrence Livermore National Laboratory
// LLNL-CODE-442911
// All rights reserved.
//
// This file is  part of VisIt. For  details, see https://visit.llnl.gov/.  The
// full copyright notice is contained in the file COPYRIGHT located at the root
// of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
//
// Redistribution  and  use  in  source  and  binary  forms,  with  or  without
// modification, are permitted provided that the following conditions are met:
//
//  - Redistributions of  source code must  retain the above  copyright notice,
//    this list of conditions and the disclaimer below.
//  - Redistributions in binary form must reproduce the above copyright notice,
//    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
//    documentation and/or other materials provided with the distribution.
//  - Neither the name of  the LLNS/LLNL nor the names of  its contributors may
//    be used to endorse or promote products derived from this software without
//    specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
// ARE  DISCLAIMED. IN  NO EVENT  SHALL LAWRENCE  LIVERMORE NATIONAL  SECURITY,
// LLC, THE  U.S.  DEPARTMENT OF  ENERGY  OR  CONTRIBUTORS BE  LIABLE  FOR  ANY
// DIRECT,  INDIRECT,   INCIDENTAL,   SPECIAL,   EXEMPLARY,  OR   CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
// SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
// CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
// LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
// OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
// DAMAGE.
//
// ***************************************************************************

package llnl.visit.plots;

import llnl.visit.AttributeSubject;
import llnl.visit.CommunicationBuffer;
import llnl.visit.Plugin;
import llnl.visit.ColorAttribute;

// ****************************************************************************
// Class: GraviTAttributes
//
// Purpose:
//    Attributes for GraviT plot
//
// Notes:      Autogenerated by xml2java.
//
// Programmer: xml2java
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

public class GraviTAttributes extends AttributeSubject implements Plugin
{
    private static int GraviTAttributes_numAdditionalAtts = 2;

    public GraviTAttributes()
    {
        super(GraviTAttributes_numAdditionalAtts);

        Color = new ColorAttribute();
        MaxReflections = 2;
    }

    public GraviTAttributes(int nMoreFields)
    {
        super(GraviTAttributes_numAdditionalAtts + nMoreFields);

        Color = new ColorAttribute();
        MaxReflections = 2;
    }

    public GraviTAttributes(GraviTAttributes obj)
    {
        super(GraviTAttributes_numAdditionalAtts);

        Color = new ColorAttribute(obj.Color);
        MaxReflections = obj.MaxReflections;

        SelectAll();
    }

    public int Offset()
    {
        return super.Offset() + super.GetNumAdditionalAttributes();
    }

    public int GetNumAdditionalAttributes()
    {
        return GraviTAttributes_numAdditionalAtts;
    }

    public boolean equals(GraviTAttributes obj)
    {
        // Create the return value
        return ((Color == obj.Color) &&
                (MaxReflections == obj.MaxReflections));
    }

    public String GetName() { return "GraviT"; }
    public String GetVersion() { return "1.0"; }

    // Property setting methods
    public void SetColor(ColorAttribute Color_)
    {
        Color = Color_;
        Select(0);
    }

    public void SetMaxReflections(int MaxReflections_)
    {
        MaxReflections = MaxReflections_;
        Select(1);
    }

    // Property getting methods
    public ColorAttribute GetColor() { return Color; }
    public int            GetMaxReflections() { return MaxReflections; }

    // Write and read methods.
    public void WriteAtts(CommunicationBuffer buf)
    {
        if(WriteSelect(0, buf))
            Color.Write(buf);
        if(WriteSelect(1, buf))
            buf.WriteInt(MaxReflections);
    }

    public void ReadAtts(int index, CommunicationBuffer buf)
    {
        switch(index)
        {
        case 0:
            Color.Read(buf);
            Select(0);
            break;
        case 1:
            SetMaxReflections(buf.ReadInt());
            break;
        }
    }

    public String toString(String indent)
    {
        String str = new String();
        str = str + indent + "Color = {" + Color.Red() + ", " + Color.Green() + ", " + Color.Blue() + ", " + Color.Alpha() + "}\n";
        str = str + intToString("MaxReflections", MaxReflections, indent) + "\n";
        return str;
    }


    // Attributes
    private ColorAttribute Color;
    private int            MaxReflections;
}

