/*****************************************************************************
*
* Copyright (c) 2000 - 2015, Lawrence Livermore National Security, LLC
* Produced at the Lawrence Livermore National Laboratory
* LLNL-CODE-442911
* All rights reserved.
*
* This file is  part of VisIt. For  details, see https://visit.llnl.gov/.  The
* full copyright notice is contained in the file COPYRIGHT located at the root
* of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
*
* Redistribution  and  use  in  source  and  binary  forms,  with  or  without
* modification, are permitted provided that the following conditions are met:
*
*  - Redistributions of  source code must  retain the above  copyright notice,
*    this list of conditions and the disclaimer below.
*  - Redistributions in binary form must reproduce the above copyright notice,
*    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
*    documentation and/or other materials provided with the distribution.
*  - Neither the name of  the LLNS/LLNL nor the names of  its contributors may
*    be used to endorse or promote products derived from this software without
*    specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
* ARE  DISCLAIMED. IN  NO EVENT  SHALL LAWRENCE  LIVERMORE NATIONAL  SECURITY,
* LLC, THE  U.S.  DEPARTMENT OF  ENERGY  OR  CONTRIBUTORS BE  LIABLE  FOR  ANY
* DIRECT,  INDIRECT,   INCIDENTAL,   SPECIAL,   EXEMPLARY,  OR   CONSEQUENTIAL
* DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
* SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
* CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
* LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
* OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
* DAMAGE.
*
*****************************************************************************/

#include <GraviTAttributes.h>
#include <DataNode.h>

//
// Enum conversion methods for GraviTAttributes::MaterialType
//

static const char *MaterialType_strings[] = {
"Lambert", "Phong", "BlinnPhong"
};

std::string
GraviTAttributes::MaterialType_ToString(GraviTAttributes::MaterialType t)
{
    int index = int(t);
    if(index < 0 || index >= 3) index = 0;
    return MaterialType_strings[index];
}

std::string
GraviTAttributes::MaterialType_ToString(int t)
{
    int index = (t < 0 || t >= 3) ? 0 : t;
    return MaterialType_strings[index];
}

bool
GraviTAttributes::MaterialType_FromString(const std::string &s, GraviTAttributes::MaterialType &val)
{
    val = GraviTAttributes::Lambert;
    for(int i = 0; i < 3; ++i)
    {
        if(s == MaterialType_strings[i])
        {
            val = (MaterialType)i;
            return true;
        }
    }
    return false;
}

// ****************************************************************************
// Method: GraviTAttributes::GraviTAttributes
//
// Purpose: 
//   Init utility for the GraviTAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void GraviTAttributes::Init()
{
    MaxReflections = 2;
    Material = BlinnPhong;

    GraviTAttributes::SelectAll();
}

// ****************************************************************************
// Method: GraviTAttributes::GraviTAttributes
//
// Purpose: 
//   Copy utility for the GraviTAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void GraviTAttributes::Copy(const GraviTAttributes &obj)
{
    DiffColor = obj.DiffColor;
    SpecColor = obj.SpecColor;
    MaxReflections = obj.MaxReflections;
    Material = obj.Material;

    GraviTAttributes::SelectAll();
}

// Type map format string
const char *GraviTAttributes::TypeMapFormatString = GRAVITATTRIBUTES_TMFS;
const AttributeGroup::private_tmfs_t GraviTAttributes::TmfsStruct = {GRAVITATTRIBUTES_TMFS};


// ****************************************************************************
// Method: GraviTAttributes::GraviTAttributes
//
// Purpose: 
//   Default constructor for the GraviTAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

GraviTAttributes::GraviTAttributes() : 
    AttributeSubject(GraviTAttributes::TypeMapFormatString),
    DiffColor(0, 20, 240), SpecColor(0, 255, 255)
{
    GraviTAttributes::Init();
}

// ****************************************************************************
// Method: GraviTAttributes::GraviTAttributes
//
// Purpose: 
//   Constructor for the derived classes of GraviTAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

GraviTAttributes::GraviTAttributes(private_tmfs_t tmfs) : 
    AttributeSubject(tmfs.tmfs),
    DiffColor(0, 20, 240), SpecColor(0, 255, 255)
{
    GraviTAttributes::Init();
}

// ****************************************************************************
// Method: GraviTAttributes::GraviTAttributes
//
// Purpose: 
//   Copy constructor for the GraviTAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

GraviTAttributes::GraviTAttributes(const GraviTAttributes &obj) : 
    AttributeSubject(GraviTAttributes::TypeMapFormatString)
{
    GraviTAttributes::Copy(obj);
}

// ****************************************************************************
// Method: GraviTAttributes::GraviTAttributes
//
// Purpose: 
//   Copy constructor for derived classes of the GraviTAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

GraviTAttributes::GraviTAttributes(const GraviTAttributes &obj, private_tmfs_t tmfs) : 
    AttributeSubject(tmfs.tmfs)
{
    GraviTAttributes::Copy(obj);
}

// ****************************************************************************
// Method: GraviTAttributes::~GraviTAttributes
//
// Purpose: 
//   Destructor for the GraviTAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

GraviTAttributes::~GraviTAttributes()
{
    // nothing here
}

// ****************************************************************************
// Method: GraviTAttributes::operator = 
//
// Purpose: 
//   Assignment operator for the GraviTAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

GraviTAttributes& 
GraviTAttributes::operator = (const GraviTAttributes &obj)
{
    if (this == &obj) return *this;

    GraviTAttributes::Copy(obj);

    return *this;
}

// ****************************************************************************
// Method: GraviTAttributes::operator == 
//
// Purpose: 
//   Comparison operator == for the GraviTAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

bool
GraviTAttributes::operator == (const GraviTAttributes &obj) const
{
    // Create the return value
    return ((DiffColor == obj.DiffColor) &&
            (SpecColor == obj.SpecColor) &&
            (MaxReflections == obj.MaxReflections) &&
            (Material == obj.Material));
}

// ****************************************************************************
// Method: GraviTAttributes::operator != 
//
// Purpose: 
//   Comparison operator != for the GraviTAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

bool
GraviTAttributes::operator != (const GraviTAttributes &obj) const
{
    return !(this->operator == (obj));
}

// ****************************************************************************
// Method: GraviTAttributes::TypeName
//
// Purpose: 
//   Type name method for the GraviTAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

const std::string
GraviTAttributes::TypeName() const
{
    return "GraviTAttributes";
}

// ****************************************************************************
// Method: GraviTAttributes::CopyAttributes
//
// Purpose: 
//   CopyAttributes method for the GraviTAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

bool
GraviTAttributes::CopyAttributes(const AttributeGroup *atts)
{
    if(TypeName() != atts->TypeName())
        return false;

    // Call assignment operator.
    const GraviTAttributes *tmp = (const GraviTAttributes *)atts;
    *this = *tmp;

    return true;
}

// ****************************************************************************
// Method: GraviTAttributes::CreateCompatible
//
// Purpose: 
//   CreateCompatible method for the GraviTAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

AttributeSubject *
GraviTAttributes::CreateCompatible(const std::string &tname) const
{
    AttributeSubject *retval = 0;
    if(TypeName() == tname)
        retval = new GraviTAttributes(*this);
    // Other cases could go here too. 

    return retval;
}

// ****************************************************************************
// Method: GraviTAttributes::NewInstance
//
// Purpose: 
//   NewInstance method for the GraviTAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

AttributeSubject *
GraviTAttributes::NewInstance(bool copy) const
{
    AttributeSubject *retval = 0;
    if(copy)
        retval = new GraviTAttributes(*this);
    else
        retval = new GraviTAttributes;

    return retval;
}

// ****************************************************************************
// Method: GraviTAttributes::SelectAll
//
// Purpose: 
//   Selects all attributes.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void
GraviTAttributes::SelectAll()
{
    Select(ID_DiffColor,      (void *)&DiffColor);
    Select(ID_SpecColor,      (void *)&SpecColor);
    Select(ID_MaxReflections, (void *)&MaxReflections);
    Select(ID_Material,       (void *)&Material);
}

///////////////////////////////////////////////////////////////////////////////
// Persistence methods
///////////////////////////////////////////////////////////////////////////////

// ****************************************************************************
// Method: GraviTAttributes::CreateNode
//
// Purpose: 
//   This method creates a DataNode representation of the object so it can be saved to a config file.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

bool
GraviTAttributes::CreateNode(DataNode *parentNode, bool completeSave, bool forceAdd)
{
    if(parentNode == 0)
        return false;

    GraviTAttributes defaultObject;
    bool addToParent = false;
    // Create a node for GraviTAttributes.
    DataNode *node = new DataNode("GraviTAttributes");

        DataNode *DiffColorNode = new DataNode("DiffColor");
        if(DiffColor.CreateNode(DiffColorNode, completeSave, true))
        {
            addToParent = true;
            node->AddNode(DiffColorNode);
        }
        else
            delete DiffColorNode;
        DataNode *SpecColorNode = new DataNode("SpecColor");
        if(SpecColor.CreateNode(SpecColorNode, completeSave, true))
        {
            addToParent = true;
            node->AddNode(SpecColorNode);
        }
        else
            delete SpecColorNode;
    if(completeSave || !FieldsEqual(ID_MaxReflections, &defaultObject))
    {
        addToParent = true;
        node->AddNode(new DataNode("MaxReflections", MaxReflections));
    }

    if(completeSave || !FieldsEqual(ID_Material, &defaultObject))
    {
        addToParent = true;
        node->AddNode(new DataNode("Material", MaterialType_ToString(Material)));
    }


    // Add the node to the parent node.
    if(addToParent || forceAdd)
        parentNode->AddNode(node);
    else
        delete node;

    return (addToParent || forceAdd);
}

// ****************************************************************************
// Method: GraviTAttributes::SetFromNode
//
// Purpose: 
//   This method sets attributes in this object from values in a DataNode representation of the object.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void
GraviTAttributes::SetFromNode(DataNode *parentNode)
{
    if(parentNode == 0)
        return;

    DataNode *searchNode = parentNode->GetNode("GraviTAttributes");
    if(searchNode == 0)
        return;

    DataNode *node;
    if((node = searchNode->GetNode("DiffColor")) != 0)
        DiffColor.SetFromNode(node);
    if((node = searchNode->GetNode("SpecColor")) != 0)
        SpecColor.SetFromNode(node);
    if((node = searchNode->GetNode("MaxReflections")) != 0)
        SetMaxReflections(node->AsInt());
    if((node = searchNode->GetNode("Material")) != 0)
    {
        // Allow enums to be int or string in the config file
        if(node->GetNodeType() == INT_NODE)
        {
            int ival = node->AsInt();
            if(ival >= 0 && ival < 3)
                SetMaterial(MaterialType(ival));
        }
        else if(node->GetNodeType() == STRING_NODE)
        {
            MaterialType value;
            if(MaterialType_FromString(node->AsString(), value))
                SetMaterial(value);
        }
    }
}

///////////////////////////////////////////////////////////////////////////////
// Set property methods
///////////////////////////////////////////////////////////////////////////////

void
GraviTAttributes::SetDiffColor(const ColorAttribute &DiffColor_)
{
    DiffColor = DiffColor_;
    Select(ID_DiffColor, (void *)&DiffColor);
}

void
GraviTAttributes::SetSpecColor(const ColorAttribute &SpecColor_)
{
    SpecColor = SpecColor_;
    Select(ID_SpecColor, (void *)&SpecColor);
}

void
GraviTAttributes::SetMaxReflections(int MaxReflections_)
{
    MaxReflections = MaxReflections_;
    Select(ID_MaxReflections, (void *)&MaxReflections);
}

void
GraviTAttributes::SetMaterial(GraviTAttributes::MaterialType Material_)
{
    Material = Material_;
    Select(ID_Material, (void *)&Material);
}

///////////////////////////////////////////////////////////////////////////////
// Get property methods
///////////////////////////////////////////////////////////////////////////////

const ColorAttribute &
GraviTAttributes::GetDiffColor() const
{
    return DiffColor;
}

ColorAttribute &
GraviTAttributes::GetDiffColor()
{
    return DiffColor;
}

const ColorAttribute &
GraviTAttributes::GetSpecColor() const
{
    return SpecColor;
}

ColorAttribute &
GraviTAttributes::GetSpecColor()
{
    return SpecColor;
}

int
GraviTAttributes::GetMaxReflections() const
{
    return MaxReflections;
}

GraviTAttributes::MaterialType
GraviTAttributes::GetMaterial() const
{
    return MaterialType(Material);
}

///////////////////////////////////////////////////////////////////////////////
// Select property methods
///////////////////////////////////////////////////////////////////////////////

void
GraviTAttributes::SelectDiffColor()
{
    Select(ID_DiffColor, (void *)&DiffColor);
}

void
GraviTAttributes::SelectSpecColor()
{
    Select(ID_SpecColor, (void *)&SpecColor);
}

///////////////////////////////////////////////////////////////////////////////
// Keyframing methods
///////////////////////////////////////////////////////////////////////////////

// ****************************************************************************
// Method: GraviTAttributes::GetFieldName
//
// Purpose: 
//   This method returns the name of a field given its index.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

std::string
GraviTAttributes::GetFieldName(int index) const
{
    switch (index)
    {
    case ID_DiffColor:      return "DiffColor";
    case ID_SpecColor:      return "SpecColor";
    case ID_MaxReflections: return "MaxReflections";
    case ID_Material:       return "Material";
    default:  return "invalid index";
    }
}

// ****************************************************************************
// Method: GraviTAttributes::GetFieldType
//
// Purpose: 
//   This method returns the type of a field given its index.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

AttributeGroup::FieldType
GraviTAttributes::GetFieldType(int index) const
{
    switch (index)
    {
    case ID_DiffColor:      return FieldType_color;
    case ID_SpecColor:      return FieldType_color;
    case ID_MaxReflections: return FieldType_int;
    case ID_Material:       return FieldType_enum;
    default:  return FieldType_unknown;
    }
}

// ****************************************************************************
// Method: GraviTAttributes::GetFieldTypeName
//
// Purpose: 
//   This method returns the name of a field type given its index.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

std::string
GraviTAttributes::GetFieldTypeName(int index) const
{
    switch (index)
    {
    case ID_DiffColor:      return "color";
    case ID_SpecColor:      return "color";
    case ID_MaxReflections: return "int";
    case ID_Material:       return "enum";
    default:  return "invalid index";
    }
}

// ****************************************************************************
// Method: GraviTAttributes::FieldsEqual
//
// Purpose: 
//   This method compares two fields and return true if they are equal.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

bool
GraviTAttributes::FieldsEqual(int index_, const AttributeGroup *rhs) const
{
    const GraviTAttributes &obj = *((const GraviTAttributes*)rhs);
    bool retval = false;
    switch (index_)
    {
    case ID_DiffColor:
        {  // new scope
        retval = (DiffColor == obj.DiffColor);
        }
        break;
    case ID_SpecColor:
        {  // new scope
        retval = (SpecColor == obj.SpecColor);
        }
        break;
    case ID_MaxReflections:
        {  // new scope
        retval = (MaxReflections == obj.MaxReflections);
        }
        break;
    case ID_Material:
        {  // new scope
        retval = (Material == obj.Material);
        }
        break;
    default: retval = false;
    }

    return retval;
}

///////////////////////////////////////////////////////////////////////////////
// User-defined methods.
///////////////////////////////////////////////////////////////////////////////

