/*****************************************************************************
*
* Copyright (c) 2000 - 2016, Lawrence Livermore National Security, LLC
* Produced at the Lawrence Livermore National Laboratory
* LLNL-CODE-442911
* All rights reserved.
*
* This file is  part of VisIt. For  details, see https://visit.llnl.gov/.  The
* full copyright notice is contained in the file COPYRIGHT located at the root
* of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
*
* Redistribution  and  use  in  source  and  binary  forms,  with  or  without
* modification, are permitted provided that the following conditions are met:
*
*  - Redistributions of  source code must  retain the above  copyright notice,
*    this list of conditions and the disclaimer below.
*  - Redistributions in binary form must reproduce the above copyright notice,
*    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
*    documentation and/or other materials provided with the distribution.
*  - Neither the name of  the LLNS/LLNL nor the names of  its contributors may
*    be used to endorse or promote products derived from this software without
*    specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
* ARE  DISCLAIMED. IN  NO EVENT  SHALL LAWRENCE  LIVERMORE NATIONAL  SECURITY,
* LLC, THE  U.S.  DEPARTMENT OF  ENERGY  OR  CONTRIBUTORS BE  LIABLE  FOR  ANY
* DIRECT,  INDIRECT,   INCIDENTAL,   SPECIAL,   EXEMPLARY,  OR   CONSEQUENTIAL
* DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
* SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
* CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
* LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
* OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
* DAMAGE.
*
*****************************************************************************/

#ifndef GRAVITATTRIBUTES_H
#define GRAVITATTRIBUTES_H
#include <string>
#include <AttributeSubject.h>

#include <ColorAttribute.h>

// ****************************************************************************
// Class: GraviTAttributes
//
// Purpose:
//    Attributes for GraviT plot
//
// Notes:      Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

class GraviTAttributes : public AttributeSubject
{
public:
    enum MaterialType
    {
        Lambert,
        Phong,
        BlinnPhong
    };
    enum Scheduler
    {
        Image,
        Domain
    };

    // These constructors are for objects of this class
    GraviTAttributes();
    GraviTAttributes(const GraviTAttributes &obj);
protected:
    // These constructors are for objects derived from this class
    GraviTAttributes(private_tmfs_t tmfs);
    GraviTAttributes(const GraviTAttributes &obj, private_tmfs_t tmfs);
public:
    virtual ~GraviTAttributes();

    virtual GraviTAttributes& operator = (const GraviTAttributes &obj);
    virtual bool operator == (const GraviTAttributes &obj) const;
    virtual bool operator != (const GraviTAttributes &obj) const;
private:
    void Init();
    void Copy(const GraviTAttributes &obj);
public:

    virtual const std::string TypeName() const;
    virtual bool CopyAttributes(const AttributeGroup *);
    virtual AttributeSubject *CreateCompatible(const std::string &) const;
    virtual AttributeSubject *NewInstance(bool) const;

    // Property selection methods
    virtual void SelectAll();
    void SelectDiffColor();
    void SelectSpecColor();

    // Property setting methods
    void SetDiffColor(const ColorAttribute &DiffColor_);
    void SetSpecColor(const ColorAttribute &SpecColor_);
    void SetMaxReflections(int MaxReflections_);
    void SetMaterial(MaterialType Material_);
    void SetScheduleType(Scheduler ScheduleType_);
    void SetSamples(int Samples_);
    void SetJitterSize(double JitterSize_);
    void SetEnableShadows(bool EnableShadows_);
    void SetLightBoost(float LightBoost_);

    // Property getting methods
    const ColorAttribute &GetDiffColor() const;
          ColorAttribute &GetDiffColor();
    const ColorAttribute &GetSpecColor() const;
          ColorAttribute &GetSpecColor();
    int                  GetMaxReflections() const;
    MaterialType         GetMaterial() const;
    Scheduler            GetScheduleType() const;
    int                  GetSamples() const;
    double               GetJitterSize() const;
    bool                 GetEnableShadows() const;
    float                GetLightBoost() const;

    // Persistence methods
    virtual bool CreateNode(DataNode *node, bool completeSave, bool forceAdd);
    virtual void SetFromNode(DataNode *node);

    // Enum conversion functions
    static std::string MaterialType_ToString(MaterialType);
    static bool MaterialType_FromString(const std::string &, MaterialType &);
protected:
    static std::string MaterialType_ToString(int);
public:
    static std::string Scheduler_ToString(Scheduler);
    static bool Scheduler_FromString(const std::string &, Scheduler &);
protected:
    static std::string Scheduler_ToString(int);
public:

    // Keyframing methods
    virtual std::string               GetFieldName(int index) const;
    virtual AttributeGroup::FieldType GetFieldType(int index) const;
    virtual std::string               GetFieldTypeName(int index) const;
    virtual bool                      FieldsEqual(int index, const AttributeGroup *rhs) const;


    // IDs that can be used to identify fields in case statements
    enum {
        ID_DiffColor = 0,
        ID_SpecColor,
        ID_MaxReflections,
        ID_Material,
        ID_ScheduleType,
        ID_Samples,
        ID_JitterSize,
        ID_EnableShadows,
        ID_LightBoost,
        ID__LAST
    };

private:
    ColorAttribute DiffColor;
    ColorAttribute SpecColor;
    int            MaxReflections;
    int            Material;
    int            ScheduleType;
    int            Samples;
    double         JitterSize;
    bool           EnableShadows;
    float          LightBoost;

    // Static class format string for type map.
    static const char *TypeMapFormatString;
    static const private_tmfs_t TmfsStruct;
};
#define GRAVITATTRIBUTES_TMFS "aaiiiidbf"

#endif
