/*****************************************************************************
*
* Copyright (c) 2000 - 2015, Lawrence Livermore National Security, LLC
* Produced at the Lawrence Livermore National Laboratory
* LLNL-CODE-442911
* All rights reserved.
*
* This file is  part of VisIt. For  details, see https://visit.llnl.gov/.  The
* full copyright notice is contained in the file COPYRIGHT located at the root
* of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
*
* Redistribution  and  use  in  source  and  binary  forms,  with  or  without
* modification, are permitted provided that the following conditions are met:
*
*  - Redistributions of  source code must  retain the above  copyright notice,
*    this list of conditions and the disclaimer below.
*  - Redistributions in binary form must reproduce the above copyright notice,
*    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
*    documentation and/or other materials provided with the distribution.
*  - Neither the name of  the LLNS/LLNL nor the names of  its contributors may
*    be used to endorse or promote products derived from this software without
*    specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
* ARE  DISCLAIMED. IN  NO EVENT  SHALL LAWRENCE  LIVERMORE NATIONAL  SECURITY,
* LLC, THE  U.S.  DEPARTMENT OF  ENERGY  OR  CONTRIBUTORS BE  LIABLE  FOR  ANY
* DIRECT,  INDIRECT,   INCIDENTAL,   SPECIAL,   EXEMPLARY,  OR   CONSEQUENTIAL
* DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
* SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
* CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
* LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
* OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
* DAMAGE.
*
*****************************************************************************/

#include <GraviTAttributes.h>
#include <DataNode.h>

// ****************************************************************************
// Method: GraviTAttributes::GraviTAttributes
//
// Purpose: 
//   Init utility for the GraviTAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void GraviTAttributes::Init()
{
    MaxReflections = 2;

    GraviTAttributes::SelectAll();
}

// ****************************************************************************
// Method: GraviTAttributes::GraviTAttributes
//
// Purpose: 
//   Copy utility for the GraviTAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void GraviTAttributes::Copy(const GraviTAttributes &obj)
{
    Color = obj.Color;
    MaxReflections = obj.MaxReflections;

    GraviTAttributes::SelectAll();
}

// Type map format string
const char *GraviTAttributes::TypeMapFormatString = GRAVITATTRIBUTES_TMFS;
const AttributeGroup::private_tmfs_t GraviTAttributes::TmfsStruct = {GRAVITATTRIBUTES_TMFS};


// ****************************************************************************
// Method: GraviTAttributes::GraviTAttributes
//
// Purpose: 
//   Default constructor for the GraviTAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

GraviTAttributes::GraviTAttributes() : 
    AttributeSubject(GraviTAttributes::TypeMapFormatString),
    Color()
{
    GraviTAttributes::Init();
}

// ****************************************************************************
// Method: GraviTAttributes::GraviTAttributes
//
// Purpose: 
//   Constructor for the derived classes of GraviTAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

GraviTAttributes::GraviTAttributes(private_tmfs_t tmfs) : 
    AttributeSubject(tmfs.tmfs),
    Color()
{
    GraviTAttributes::Init();
}

// ****************************************************************************
// Method: GraviTAttributes::GraviTAttributes
//
// Purpose: 
//   Copy constructor for the GraviTAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

GraviTAttributes::GraviTAttributes(const GraviTAttributes &obj) : 
    AttributeSubject(GraviTAttributes::TypeMapFormatString)
{
    GraviTAttributes::Copy(obj);
}

// ****************************************************************************
// Method: GraviTAttributes::GraviTAttributes
//
// Purpose: 
//   Copy constructor for derived classes of the GraviTAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

GraviTAttributes::GraviTAttributes(const GraviTAttributes &obj, private_tmfs_t tmfs) : 
    AttributeSubject(tmfs.tmfs)
{
    GraviTAttributes::Copy(obj);
}

// ****************************************************************************
// Method: GraviTAttributes::~GraviTAttributes
//
// Purpose: 
//   Destructor for the GraviTAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

GraviTAttributes::~GraviTAttributes()
{
    // nothing here
}

// ****************************************************************************
// Method: GraviTAttributes::operator = 
//
// Purpose: 
//   Assignment operator for the GraviTAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

GraviTAttributes& 
GraviTAttributes::operator = (const GraviTAttributes &obj)
{
    if (this == &obj) return *this;

    GraviTAttributes::Copy(obj);

    return *this;
}

// ****************************************************************************
// Method: GraviTAttributes::operator == 
//
// Purpose: 
//   Comparison operator == for the GraviTAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

bool
GraviTAttributes::operator == (const GraviTAttributes &obj) const
{
    // Create the return value
    return ((Color == obj.Color) &&
            (MaxReflections == obj.MaxReflections));
}

// ****************************************************************************
// Method: GraviTAttributes::operator != 
//
// Purpose: 
//   Comparison operator != for the GraviTAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

bool
GraviTAttributes::operator != (const GraviTAttributes &obj) const
{
    return !(this->operator == (obj));
}

// ****************************************************************************
// Method: GraviTAttributes::TypeName
//
// Purpose: 
//   Type name method for the GraviTAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

const std::string
GraviTAttributes::TypeName() const
{
    return "GraviTAttributes";
}

// ****************************************************************************
// Method: GraviTAttributes::CopyAttributes
//
// Purpose: 
//   CopyAttributes method for the GraviTAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

bool
GraviTAttributes::CopyAttributes(const AttributeGroup *atts)
{
    if(TypeName() != atts->TypeName())
        return false;

    // Call assignment operator.
    const GraviTAttributes *tmp = (const GraviTAttributes *)atts;
    *this = *tmp;

    return true;
}

// ****************************************************************************
// Method: GraviTAttributes::CreateCompatible
//
// Purpose: 
//   CreateCompatible method for the GraviTAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

AttributeSubject *
GraviTAttributes::CreateCompatible(const std::string &tname) const
{
    AttributeSubject *retval = 0;
    if(TypeName() == tname)
        retval = new GraviTAttributes(*this);
    // Other cases could go here too. 

    return retval;
}

// ****************************************************************************
// Method: GraviTAttributes::NewInstance
//
// Purpose: 
//   NewInstance method for the GraviTAttributes class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

AttributeSubject *
GraviTAttributes::NewInstance(bool copy) const
{
    AttributeSubject *retval = 0;
    if(copy)
        retval = new GraviTAttributes(*this);
    else
        retval = new GraviTAttributes;

    return retval;
}

// ****************************************************************************
// Method: GraviTAttributes::SelectAll
//
// Purpose: 
//   Selects all attributes.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void
GraviTAttributes::SelectAll()
{
    Select(ID_Color,          (void *)&Color);
    Select(ID_MaxReflections, (void *)&MaxReflections);
}

///////////////////////////////////////////////////////////////////////////////
// Persistence methods
///////////////////////////////////////////////////////////////////////////////

// ****************************************************************************
// Method: GraviTAttributes::CreateNode
//
// Purpose: 
//   This method creates a DataNode representation of the object so it can be saved to a config file.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

bool
GraviTAttributes::CreateNode(DataNode *parentNode, bool completeSave, bool forceAdd)
{
    if(parentNode == 0)
        return false;

    GraviTAttributes defaultObject;
    bool addToParent = false;
    // Create a node for GraviTAttributes.
    DataNode *node = new DataNode("GraviTAttributes");

        DataNode *ColorNode = new DataNode("Color");
        if(Color.CreateNode(ColorNode, completeSave, true))
        {
            addToParent = true;
            node->AddNode(ColorNode);
        }
        else
            delete ColorNode;
    if(completeSave || !FieldsEqual(ID_MaxReflections, &defaultObject))
    {
        addToParent = true;
        node->AddNode(new DataNode("MaxReflections", MaxReflections));
    }


    // Add the node to the parent node.
    if(addToParent || forceAdd)
        parentNode->AddNode(node);
    else
        delete node;

    return (addToParent || forceAdd);
}

// ****************************************************************************
// Method: GraviTAttributes::SetFromNode
//
// Purpose: 
//   This method sets attributes in this object from values in a DataNode representation of the object.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void
GraviTAttributes::SetFromNode(DataNode *parentNode)
{
    if(parentNode == 0)
        return;

    DataNode *searchNode = parentNode->GetNode("GraviTAttributes");
    if(searchNode == 0)
        return;

    DataNode *node;
    if((node = searchNode->GetNode("Color")) != 0)
        Color.SetFromNode(node);
    if((node = searchNode->GetNode("MaxReflections")) != 0)
        SetMaxReflections(node->AsInt());
}

///////////////////////////////////////////////////////////////////////////////
// Set property methods
///////////////////////////////////////////////////////////////////////////////

void
GraviTAttributes::SetColor(const ColorAttribute &Color_)
{
    Color = Color_;
    Select(ID_Color, (void *)&Color);
}

void
GraviTAttributes::SetMaxReflections(int MaxReflections_)
{
    MaxReflections = MaxReflections_;
    Select(ID_MaxReflections, (void *)&MaxReflections);
}

///////////////////////////////////////////////////////////////////////////////
// Get property methods
///////////////////////////////////////////////////////////////////////////////

const ColorAttribute &
GraviTAttributes::GetColor() const
{
    return Color;
}

ColorAttribute &
GraviTAttributes::GetColor()
{
    return Color;
}

int
GraviTAttributes::GetMaxReflections() const
{
    return MaxReflections;
}

///////////////////////////////////////////////////////////////////////////////
// Select property methods
///////////////////////////////////////////////////////////////////////////////

void
GraviTAttributes::SelectColor()
{
    Select(ID_Color, (void *)&Color);
}

///////////////////////////////////////////////////////////////////////////////
// Keyframing methods
///////////////////////////////////////////////////////////////////////////////

// ****************************************************************************
// Method: GraviTAttributes::GetFieldName
//
// Purpose: 
//   This method returns the name of a field given its index.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

std::string
GraviTAttributes::GetFieldName(int index) const
{
    switch (index)
    {
    case ID_Color:          return "Color";
    case ID_MaxReflections: return "MaxReflections";
    default:  return "invalid index";
    }
}

// ****************************************************************************
// Method: GraviTAttributes::GetFieldType
//
// Purpose: 
//   This method returns the type of a field given its index.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

AttributeGroup::FieldType
GraviTAttributes::GetFieldType(int index) const
{
    switch (index)
    {
    case ID_Color:          return FieldType_color;
    case ID_MaxReflections: return FieldType_int;
    default:  return FieldType_unknown;
    }
}

// ****************************************************************************
// Method: GraviTAttributes::GetFieldTypeName
//
// Purpose: 
//   This method returns the name of a field type given its index.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

std::string
GraviTAttributes::GetFieldTypeName(int index) const
{
    switch (index)
    {
    case ID_Color:          return "color";
    case ID_MaxReflections: return "int";
    default:  return "invalid index";
    }
}

// ****************************************************************************
// Method: GraviTAttributes::FieldsEqual
//
// Purpose: 
//   This method compares two fields and return true if they are equal.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

bool
GraviTAttributes::FieldsEqual(int index_, const AttributeGroup *rhs) const
{
    const GraviTAttributes &obj = *((const GraviTAttributes*)rhs);
    bool retval = false;
    switch (index_)
    {
    case ID_Color:
        {  // new scope
        retval = (Color == obj.Color);
        }
        break;
    case ID_MaxReflections:
        {  // new scope
        retval = (MaxReflections == obj.MaxReflections);
        }
        break;
    default: retval = false;
    }

    return retval;
}

///////////////////////////////////////////////////////////////////////////////
// User-defined methods.
///////////////////////////////////////////////////////////////////////////////

