/*****************************************************************************
*
* Copyright (c) 2000 - 2015, Lawrence Livermore National Security, LLC
* Produced at the Lawrence Livermore National Laboratory
* LLNL-CODE-442911
* All rights reserved.
*
* This file is  part of VisIt. For  details, see https://visit.llnl.gov/.  The
* full copyright notice is contained in the file COPYRIGHT located at the root
* of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
*
* Redistribution  and  use  in  source  and  binary  forms,  with  or  without
* modification, are permitted provided that the following conditions are met:
*
*  - Redistributions of  source code must  retain the above  copyright notice,
*    this list of conditions and the disclaimer below.
*  - Redistributions in binary form must reproduce the above copyright notice,
*    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
*    documentation and/or other materials provided with the distribution.
*  - Neither the name of  the LLNS/LLNL nor the names of  its contributors may
*    be used to endorse or promote products derived from this software without
*    specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
* ARE  DISCLAIMED. IN  NO EVENT  SHALL LAWRENCE  LIVERMORE NATIONAL  SECURITY,
* LLC, THE  U.S.  DEPARTMENT OF  ENERGY  OR  CONTRIBUTORS BE  LIABLE  FOR  ANY
* DIRECT,  INDIRECT,   INCIDENTAL,   SPECIAL,   EXEMPLARY,  OR   CONSEQUENTIAL
* DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
* SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
* CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
* LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
* OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
* DAMAGE.
*
*****************************************************************************/

#include <PyGraviTAttributes.h>
#include <ObserverToCallback.h>
#include <stdio.h>
#include <snprintf.h>
#include <ColorAttribute.h>

// ****************************************************************************
// Module: PyGraviTAttributes
//
// Purpose: 
//   Attributes for GraviT plot
//
// Note:       Autogenerated by xml2python. Do not modify by hand!
//
// Programmer: xml2python
// Creation:   omitted
//
// ****************************************************************************

//
// This struct contains the Python type information and a GraviTAttributes.
//
struct GraviTAttributesObject
{
    PyObject_HEAD
    GraviTAttributes *data;
    bool        owns;
    PyObject   *parent;
};

//
// Internal prototypes
//
static PyObject *NewGraviTAttributes(int);

std::string
PyGraviTAttributes_ToString(const GraviTAttributes *atts, const char *prefix)
{
    std::string str;
    char tmpStr[1000];

    const unsigned char *Color = atts->GetColor().GetColor();
    SNPRINTF(tmpStr, 1000, "%sColor = (%d, %d, %d, %d)\n", prefix, int(Color[0]), int(Color[1]), int(Color[2]), int(Color[3]));
    str += tmpStr;
    SNPRINTF(tmpStr, 1000, "%sMaxReflections = %d\n", prefix, atts->GetMaxReflections());
    str += tmpStr;
    return str;
}

static PyObject *
GraviTAttributes_Notify(PyObject *self, PyObject *args)
{
    GraviTAttributesObject *obj = (GraviTAttributesObject *)self;
    obj->data->Notify();
    Py_INCREF(Py_None);
    return Py_None;
}

/*static*/ PyObject *
GraviTAttributes_SetColor(PyObject *self, PyObject *args)
{
    GraviTAttributesObject *obj = (GraviTAttributesObject *)self;

    int c[4];
    if(!PyArg_ParseTuple(args, "iiii", &c[0], &c[1], &c[2], &c[3]))
    {
        c[3] = 255;
        if(!PyArg_ParseTuple(args, "iii", &c[0], &c[1], &c[2]))
        {
            double dr, dg, db, da;
            if(PyArg_ParseTuple(args, "dddd", &dr, &dg, &db, &da))
            {
                c[0] = int(dr);
                c[1] = int(dg);
                c[2] = int(db);
                c[3] = int(da);
            }
            else if(PyArg_ParseTuple(args, "ddd", &dr, &dg, &db))
            {
                c[0] = int(dr);
                c[1] = int(dg);
                c[2] = int(db);
                c[3] = 255;
            }
            else
            {
                PyObject *tuple = NULL;
                if(!PyArg_ParseTuple(args, "O", &tuple))
                    return NULL;

                if(!PyTuple_Check(tuple))
                    return NULL;

                // Make sure that the tuple is the right size.
                if(PyTuple_Size(tuple) < 3 || PyTuple_Size(tuple) > 4)
                    return NULL;

                // Make sure that all elements in the tuple are ints.
                for(int i = 0; i < PyTuple_Size(tuple); ++i)
                {
                    PyObject *item = PyTuple_GET_ITEM(tuple, i);
                    if(PyInt_Check(item))
                        c[i] = int(PyInt_AS_LONG(PyTuple_GET_ITEM(tuple, i)));
                    else if(PyFloat_Check(item))
                        c[i] = int(PyFloat_AS_DOUBLE(PyTuple_GET_ITEM(tuple, i)));
                    else
                        return NULL;
                }
            }
        }
        PyErr_Clear();
    }

    // Set the Color in the object.
    ColorAttribute ca(c[0], c[1], c[2], c[3]);
    obj->data->SetColor(ca);

    Py_INCREF(Py_None);
    return Py_None;
}

/*static*/ PyObject *
GraviTAttributes_GetColor(PyObject *self, PyObject *args)
{
    GraviTAttributesObject *obj = (GraviTAttributesObject *)self;
    // Allocate a tuple the with enough entries to hold the Color.
    PyObject *retval = PyTuple_New(4);
    const unsigned char *Color = obj->data->GetColor().GetColor();
    PyTuple_SET_ITEM(retval, 0, PyInt_FromLong(long(Color[0])));
    PyTuple_SET_ITEM(retval, 1, PyInt_FromLong(long(Color[1])));
    PyTuple_SET_ITEM(retval, 2, PyInt_FromLong(long(Color[2])));
    PyTuple_SET_ITEM(retval, 3, PyInt_FromLong(long(Color[3])));
    return retval;
}

/*static*/ PyObject *
GraviTAttributes_SetMaxReflections(PyObject *self, PyObject *args)
{
    GraviTAttributesObject *obj = (GraviTAttributesObject *)self;

    int ival;
    if(!PyArg_ParseTuple(args, "i", &ival))
        return NULL;

    // Set the MaxReflections in the object.
    obj->data->SetMaxReflections((int)ival);

    Py_INCREF(Py_None);
    return Py_None;
}

/*static*/ PyObject *
GraviTAttributes_GetMaxReflections(PyObject *self, PyObject *args)
{
    GraviTAttributesObject *obj = (GraviTAttributesObject *)self;
    PyObject *retval = PyInt_FromLong(long(obj->data->GetMaxReflections()));
    return retval;
}



PyMethodDef PyGraviTAttributes_methods[GRAVITATTRIBUTES_NMETH] = {
    {"Notify", GraviTAttributes_Notify, METH_VARARGS},
    {"SetColor", GraviTAttributes_SetColor, METH_VARARGS},
    {"GetColor", GraviTAttributes_GetColor, METH_VARARGS},
    {"SetMaxReflections", GraviTAttributes_SetMaxReflections, METH_VARARGS},
    {"GetMaxReflections", GraviTAttributes_GetMaxReflections, METH_VARARGS},
    {NULL, NULL}
};

//
// Type functions
//

static void
GraviTAttributes_dealloc(PyObject *v)
{
   GraviTAttributesObject *obj = (GraviTAttributesObject *)v;
   if(obj->parent != 0)
       Py_DECREF(obj->parent);
   if(obj->owns)
       delete obj->data;
}

static int
GraviTAttributes_compare(PyObject *v, PyObject *w)
{
    GraviTAttributes *a = ((GraviTAttributesObject *)v)->data;
    GraviTAttributes *b = ((GraviTAttributesObject *)w)->data;
    return (*a == *b) ? 0 : -1;
}

PyObject *
PyGraviTAttributes_getattr(PyObject *self, char *name)
{
    if(strcmp(name, "Color") == 0)
        return GraviTAttributes_GetColor(self, NULL);
    if(strcmp(name, "MaxReflections") == 0)
        return GraviTAttributes_GetMaxReflections(self, NULL);

    return Py_FindMethod(PyGraviTAttributes_methods, self, name);
}

int
PyGraviTAttributes_setattr(PyObject *self, char *name, PyObject *args)
{
    // Create a tuple to contain the arguments since all of the Set
    // functions expect a tuple.
    PyObject *tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(tuple, 0, args);
    Py_INCREF(args);
    PyObject *obj = NULL;

    if(strcmp(name, "Color") == 0)
        obj = GraviTAttributes_SetColor(self, tuple);
    else if(strcmp(name, "MaxReflections") == 0)
        obj = GraviTAttributes_SetMaxReflections(self, tuple);

    if(obj != NULL)
        Py_DECREF(obj);

    Py_DECREF(tuple);
    if( obj == NULL)
        PyErr_Format(PyExc_RuntimeError, "Unable to set unknown attribute: '%s'", name);
    return (obj != NULL) ? 0 : -1;
}

static int
GraviTAttributes_print(PyObject *v, FILE *fp, int flags)
{
    GraviTAttributesObject *obj = (GraviTAttributesObject *)v;
    fprintf(fp, "%s", PyGraviTAttributes_ToString(obj->data, "").c_str());
    return 0;
}

PyObject *
GraviTAttributes_str(PyObject *v)
{
    GraviTAttributesObject *obj = (GraviTAttributesObject *)v;
    return PyString_FromString(PyGraviTAttributes_ToString(obj->data,"").c_str());
}

//
// The doc string for the class.
//
#if PY_MAJOR_VERSION > 2 || (PY_MAJOR_VERSION == 2 && PY_MINOR_VERSION >= 5)
static const char *GraviTAttributes_Purpose = "Attributes for GraviT plot";
#else
static char *GraviTAttributes_Purpose = "Attributes for GraviT plot";
#endif

//
// The type description structure
//
static PyTypeObject GraviTAttributesType =
{
    //
    // Type header
    //
    PyObject_HEAD_INIT(&PyType_Type)
    0,                                   // ob_size
    "GraviTAttributes",                    // tp_name
    sizeof(GraviTAttributesObject),        // tp_basicsize
    0,                                   // tp_itemsize
    //
    // Standard methods
    //
    (destructor)GraviTAttributes_dealloc,  // tp_dealloc
    (printfunc)GraviTAttributes_print,     // tp_print
    (getattrfunc)PyGraviTAttributes_getattr, // tp_getattr
    (setattrfunc)PyGraviTAttributes_setattr, // tp_setattr
    (cmpfunc)GraviTAttributes_compare,     // tp_compare
    (reprfunc)0,                         // tp_repr
    //
    // Type categories
    //
    0,                                   // tp_as_number
    0,                                   // tp_as_sequence
    0,                                   // tp_as_mapping
    //
    // More methods
    //
    0,                                   // tp_hash
    0,                                   // tp_call
    (reprfunc)GraviTAttributes_str,        // tp_str
    0,                                   // tp_getattro
    0,                                   // tp_setattro
    0,                                   // tp_as_buffer
    Py_TPFLAGS_CHECKTYPES,               // tp_flags
    GraviTAttributes_Purpose,              // tp_doc
    0,                                   // tp_traverse
    0,                                   // tp_clear
    0,                                   // tp_richcompare
    0                                    // tp_weaklistoffset
};

//
// Helper functions for object allocation.
//

static GraviTAttributes *defaultAtts = 0;
static GraviTAttributes *currentAtts = 0;

static PyObject *
NewGraviTAttributes(int useCurrent)
{
    GraviTAttributesObject *newObject;
    newObject = PyObject_NEW(GraviTAttributesObject, &GraviTAttributesType);
    if(newObject == NULL)
        return NULL;
    if(useCurrent && currentAtts != 0)
        newObject->data = new GraviTAttributes(*currentAtts);
    else if(defaultAtts != 0)
        newObject->data = new GraviTAttributes(*defaultAtts);
    else
        newObject->data = new GraviTAttributes;
    newObject->owns = true;
    newObject->parent = 0;
    return (PyObject *)newObject;
}

static PyObject *
WrapGraviTAttributes(const GraviTAttributes *attr)
{
    GraviTAttributesObject *newObject;
    newObject = PyObject_NEW(GraviTAttributesObject, &GraviTAttributesType);
    if(newObject == NULL)
        return NULL;
    newObject->data = (GraviTAttributes *)attr;
    newObject->owns = false;
    newObject->parent = 0;
    return (PyObject *)newObject;
}

///////////////////////////////////////////////////////////////////////////////
//
// Interface that is exposed to the VisIt module.
//
///////////////////////////////////////////////////////////////////////////////

PyObject *
GraviTAttributes_new(PyObject *self, PyObject *args)
{
    int useCurrent = 0;
    if (!PyArg_ParseTuple(args, "i", &useCurrent))
    {
        if (!PyArg_ParseTuple(args, ""))
            return NULL;
        else
            PyErr_Clear();
    }

    return (PyObject *)NewGraviTAttributes(useCurrent);
}

//
// Plugin method table. These methods are added to the visitmodule's methods.
//
static PyMethodDef GraviTAttributesMethods[] = {
    {"GraviTAttributes", GraviTAttributes_new, METH_VARARGS},
    {NULL,      NULL}        /* Sentinel */
};

static Observer *GraviTAttributesObserver = 0;

std::string
PyGraviTAttributes_GetLogString()
{
    std::string s("GraviTAtts = GraviTAttributes()\n");
    if(currentAtts != 0)
        s += PyGraviTAttributes_ToString(currentAtts, "GraviTAtts.");
    return s;
}

static void
PyGraviTAttributes_CallLogRoutine(Subject *subj, void *data)
{
    typedef void (*logCallback)(const std::string &);
    logCallback cb = (logCallback)data;

    if(cb != 0)
    {
        std::string s("GraviTAtts = GraviTAttributes()\n");
        s += PyGraviTAttributes_ToString(currentAtts, "GraviTAtts.");
        cb(s);
    }
}

void
PyGraviTAttributes_StartUp(GraviTAttributes *subj, void *data)
{
    if(subj == 0)
        return;

    currentAtts = subj;
    PyGraviTAttributes_SetDefaults(subj);

    //
    // Create the observer that will be notified when the attributes change.
    //
    if(GraviTAttributesObserver == 0)
    {
        GraviTAttributesObserver = new ObserverToCallback(subj,
            PyGraviTAttributes_CallLogRoutine, (void *)data);
    }

}

void
PyGraviTAttributes_CloseDown()
{
    delete defaultAtts;
    defaultAtts = 0;
    delete GraviTAttributesObserver;
    GraviTAttributesObserver = 0;
}

PyMethodDef *
PyGraviTAttributes_GetMethodTable(int *nMethods)
{
    *nMethods = 1;
    return GraviTAttributesMethods;
}

bool
PyGraviTAttributes_Check(PyObject *obj)
{
    return (obj->ob_type == &GraviTAttributesType);
}

GraviTAttributes *
PyGraviTAttributes_FromPyObject(PyObject *obj)
{
    GraviTAttributesObject *obj2 = (GraviTAttributesObject *)obj;
    return obj2->data;
}

PyObject *
PyGraviTAttributes_New()
{
    return NewGraviTAttributes(0);
}

PyObject *
PyGraviTAttributes_Wrap(const GraviTAttributes *attr)
{
    return WrapGraviTAttributes(attr);
}

void
PyGraviTAttributes_SetParent(PyObject *obj, PyObject *parent)
{
    GraviTAttributesObject *obj2 = (GraviTAttributesObject *)obj;
    obj2->parent = parent;
}

void
PyGraviTAttributes_SetDefaults(const GraviTAttributes *atts)
{
    if(defaultAtts)
        delete defaultAtts;

    defaultAtts = new GraviTAttributes(*atts);
}

