/*****************************************************************************
*
* Copyright (c) 2000 - 2015, Lawrence Livermore National Security, LLC
* Produced at the Lawrence Livermore National Laboratory
* LLNL-CODE-442911
* All rights reserved.
*
* This file is  part of VisIt. For  details, see https://visit.llnl.gov/.  The
* full copyright notice is contained in the file COPYRIGHT located at the root
* of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
*
* Redistribution  and  use  in  source  and  binary  forms,  with  or  without
* modification, are permitted provided that the following conditions are met:
*
*  - Redistributions of  source code must  retain the above  copyright notice,
*    this list of conditions and the disclaimer below.
*  - Redistributions in binary form must reproduce the above copyright notice,
*    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
*    documentation and/or other materials provided with the distribution.
*  - Neither the name of  the LLNS/LLNL nor the names of  its contributors may
*    be used to endorse or promote products derived from this software without
*    specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
* ARE  DISCLAIMED. IN  NO EVENT  SHALL LAWRENCE  LIVERMORE NATIONAL  SECURITY,
* LLC, THE  U.S.  DEPARTMENT OF  ENERGY  OR  CONTRIBUTORS BE  LIABLE  FOR  ANY
* DIRECT,  INDIRECT,   INCIDENTAL,   SPECIAL,   EXEMPLARY,  OR   CONSEQUENTIAL
* DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
* SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
* CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
* LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
* OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
* DAMAGE.
*
*****************************************************************************/

#include "QvisGraviTPlotWindow.h"

#include <GraviTAttributes.h>
#include <ViewerProxy.h>

#include <QCheckBox>
#include <QLabel>
#include <QLayout>
#include <QLineEdit>
#include <QSpinBox>
#include <QButtonGroup>
#include <QRadioButton>
#include <QvisColorTableButton.h>
#include <QvisOpacitySlider.h>
#include <QvisColorButton.h>
#include <QvisLineStyleWidget.h>
#include <QvisLineWidthWidget.h>
#include <QvisVariableButton.h>

#include <stdio.h>
#include <string>

using std::string;

// ****************************************************************************
// Method: QvisGraviTPlotWindow::QvisGraviTPlotWindow
//
// Purpose: 
//   Constructor
//
// Note:       Autogenerated by xml2window.
//
// Programmer: xml2window
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

QvisGraviTPlotWindow::QvisGraviTPlotWindow(const int type,
                         GraviTAttributes *subj,
                         const QString &caption,
                         const QString &shortName,
                         QvisNotepadArea *notepad)
    : QvisPostableWindowObserver(subj, caption, shortName, notepad)
{
    plotType = type;
    atts = subj;
}


// ****************************************************************************
// Method: QvisGraviTPlotWindow::~QvisGraviTPlotWindow
//
// Purpose: 
//   Destructor
//
// Note:       Autogenerated by xml2window.
//
// Programmer: xml2window
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

QvisGraviTPlotWindow::~QvisGraviTPlotWindow()
{
}


// ****************************************************************************
// Method: QvisGraviTPlotWindow::CreateWindowContents
//
// Purpose: 
//   Creates the widgets for the window.
//
// Note:       Autogenerated by xml2window.
//
// Programmer: xml2window
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void
QvisGraviTPlotWindow::CreateWindowContents()
{
    QGridLayout *mainLayout = new QGridLayout(0);
    topLayout->addLayout(mainLayout);

    DiffColorLabel = new QLabel(tr("Diffuse Color"), central);
    mainLayout->addWidget(DiffColorLabel,0,0);
    DiffColor = new QvisColorButton(central);
    connect(DiffColor, SIGNAL(selectedColor(const QColor&)),
            this, SLOT(DiffColorChanged(const QColor&)));
    mainLayout->addWidget(DiffColor, 0,1);

    SpecColorLabel = new QLabel(tr("Specular Color"), central);
    mainLayout->addWidget(SpecColorLabel,1,0);
    SpecColor = new QvisColorButton(central);
    connect(SpecColor, SIGNAL(selectedColor(const QColor&)),
            this, SLOT(SpecColorChanged(const QColor&)));
    mainLayout->addWidget(SpecColor, 1,1);

    MaxReflectionsLabel = new QLabel(tr("Maximum number of reflections"), central);
    mainLayout->addWidget(MaxReflectionsLabel,2,0);
    MaxReflections = new QLineEdit(central);
    connect(MaxReflections, SIGNAL(returnPressed()),
            this, SLOT(MaxReflectionsProcessText()));
    mainLayout->addWidget(MaxReflections, 2,1);

    MaterialLabel = new QLabel(tr("Material"), central);
    mainLayout->addWidget(MaterialLabel,3,0);
    Material = new QWidget(central);
    MaterialButtonGroup= new QButtonGroup(Material);
    QHBoxLayout *MaterialLayout = new QHBoxLayout(Material);
    MaterialLayout->setMargin(0);
    MaterialLayout->setSpacing(10);
    QRadioButton *MaterialMaterialTypeLambert = new QRadioButton(tr("Lambert"), Material);
    MaterialButtonGroup->addButton(MaterialMaterialTypeLambert,0);
    MaterialLayout->addWidget(MaterialMaterialTypeLambert);
    QRadioButton *MaterialMaterialTypePhong = new QRadioButton(tr("Phong"), Material);
    MaterialButtonGroup->addButton(MaterialMaterialTypePhong,1);
    MaterialLayout->addWidget(MaterialMaterialTypePhong);
    QRadioButton *MaterialMaterialTypeBlinnPhong = new QRadioButton(tr("BlinnPhong"), Material);
    MaterialButtonGroup->addButton(MaterialMaterialTypeBlinnPhong,2);
    MaterialLayout->addWidget(MaterialMaterialTypeBlinnPhong);
    connect(MaterialButtonGroup, SIGNAL(buttonClicked(int)),
            this, SLOT(MaterialChanged(int)));
    mainLayout->addWidget(Material, 3,1);

    ScheduleTypeLabel = new QLabel(tr("Schedule Type"), central);
    mainLayout->addWidget(ScheduleTypeLabel,4,0);
    ScheduleType = new QWidget(central);
    ScheduleTypeButtonGroup= new QButtonGroup(ScheduleType);
    QHBoxLayout *ScheduleTypeLayout = new QHBoxLayout(ScheduleType);
    ScheduleTypeLayout->setMargin(0);
    ScheduleTypeLayout->setSpacing(10);
    QRadioButton *ScheduleTypeSchedulerImage = new QRadioButton(tr("Image"), ScheduleType);
    ScheduleTypeButtonGroup->addButton(ScheduleTypeSchedulerImage,0);
    ScheduleTypeLayout->addWidget(ScheduleTypeSchedulerImage);
    QRadioButton *ScheduleTypeSchedulerDomain = new QRadioButton(tr("Domain"), ScheduleType);
    ScheduleTypeButtonGroup->addButton(ScheduleTypeSchedulerDomain,1);
    ScheduleTypeLayout->addWidget(ScheduleTypeSchedulerDomain);
    connect(ScheduleTypeButtonGroup, SIGNAL(buttonClicked(int)),
            this, SLOT(ScheduleTypeChanged(int)));
    mainLayout->addWidget(ScheduleType, 4,1);

    SamplesLabel = new QLabel(tr("Samples"), central);
    mainLayout->addWidget(SamplesLabel,5,0);
    Samples = new QLineEdit(central);
    connect(Samples, SIGNAL(returnPressed()),
            this, SLOT(SamplesProcessText()));
    mainLayout->addWidget(Samples, 5,1);

    JitterSizeLabel = new QLabel(tr("JitterSize"), central);
    mainLayout->addWidget(JitterSizeLabel,6,0);
    JitterSize = new QLineEdit(central);
    connect(JitterSize, SIGNAL(returnPressed()),
            this, SLOT(JitterSizeProcessText()));
    mainLayout->addWidget(JitterSize, 6,1);

}


// ****************************************************************************
// Method: QvisGraviTPlotWindow::UpdateWindow
//
// Purpose: 
//   Updates the widgets in the window when the subject changes.
//
// Note:       Autogenerated by xml2window.
//
// Programmer: xml2window
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void
QvisGraviTPlotWindow::UpdateWindow(bool doAll)
{

    for(int i = 0; i < atts->NumAttributes(); ++i)
    {
        if(!doAll)
        {
            if(!atts->IsSelected(i))
            {
                continue;
            }
        }

        switch(i)
        {
          case GraviTAttributes::ID_DiffColor:
            { // new scope
                QColor tempcolor = QColor(atts->GetDiffColor().Red(),
                                   atts->GetDiffColor().Green(),
                                   atts->GetDiffColor().Blue());
                DiffColor->blockSignals(true);
                DiffColor->setButtonColor(tempcolor);
                DiffColor->blockSignals(false);
            }
            break;
          case GraviTAttributes::ID_SpecColor:
            { // new scope
                QColor tempcolor = QColor(atts->GetSpecColor().Red(),
                                   atts->GetSpecColor().Green(),
                                   atts->GetSpecColor().Blue());
                SpecColor->blockSignals(true);
                SpecColor->setButtonColor(tempcolor);
                SpecColor->blockSignals(false);
            }
            break;
          case GraviTAttributes::ID_MaxReflections:
            MaxReflections->setText(IntToQString(atts->GetMaxReflections()));
            break;
          case GraviTAttributes::ID_Material:
            MaterialButtonGroup->blockSignals(true);
            if(MaterialButtonGroup->button((int)atts->GetMaterial()) != 0)
                MaterialButtonGroup->button((int)atts->GetMaterial())->setChecked(true);
            MaterialButtonGroup->blockSignals(false);
            break;
          case GraviTAttributes::ID_ScheduleType:
            ScheduleTypeButtonGroup->blockSignals(true);
            if(ScheduleTypeButtonGroup->button((int)atts->GetScheduleType()) != 0)
                ScheduleTypeButtonGroup->button((int)atts->GetScheduleType())->setChecked(true);
            ScheduleTypeButtonGroup->blockSignals(false);
            break;
          case GraviTAttributes::ID_Samples:
            Samples->setText(IntToQString(atts->GetSamples()));
            break;
          case GraviTAttributes::ID_JitterSize:
            JitterSize->setText(DoubleToQString(atts->GetJitterSize()));
            break;
        }
    }
}


// ****************************************************************************
// Method: QvisGraviTPlotWindow::GetCurrentValues
//
// Purpose: 
//   Gets values from certain widgets and stores them in the subject.
//
// Note:       Autogenerated by xml2window.
//
// Programmer: xml2window
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void
QvisGraviTPlotWindow::GetCurrentValues(int which_widget)
{
    bool doAll = (which_widget == -1);

    // Do MaxReflections
    if(which_widget == GraviTAttributes::ID_MaxReflections || doAll)
    {
        int val;
        if(LineEditGetInt(MaxReflections, val))
            atts->SetMaxReflections(val);
        else
        {
            ResettingError(tr("Maximum number of reflections"),
                IntToQString(atts->GetMaxReflections()));
            atts->SetMaxReflections(atts->GetMaxReflections());
        }
    }

    // Do Samples
    if(which_widget == GraviTAttributes::ID_Samples || doAll)
    {
        int val;
        if(LineEditGetInt(Samples, val))
            atts->SetSamples(val);
        else
        {
            ResettingError(tr("Samples"),
                IntToQString(atts->GetSamples()));
            atts->SetSamples(atts->GetSamples());
        }
    }

    // Do JitterSize
    if(which_widget == GraviTAttributes::ID_JitterSize || doAll)
    {
        double val;
        if(LineEditGetDouble(JitterSize, val))
            atts->SetJitterSize(val);
        else
        {
            ResettingError(tr("JitterSize"),
                DoubleToQString(atts->GetJitterSize()));
            atts->SetJitterSize(atts->GetJitterSize());
        }
    }

}


// ****************************************************************************
// Method: QvisGraviTPlotWindow::Apply
//
// Purpose: 
//   Called to apply changes in the subject.
//
// Note:       Autogenerated by xml2window.
//
// Programmer: xml2window
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void
QvisGraviTPlotWindow::Apply(bool ignore)
{
    if(AutoUpdate() || ignore)
    {
        GetCurrentValues(-1);
        atts->Notify();

        GetViewerMethods()->SetPlotOptions(plotType);
    }
    else
        atts->Notify();
}


//
// Qt Slot functions
//


// ****************************************************************************
// Method: QvisGraviTPlotWindow::apply
//
// Purpose: 
//   Qt slot function called when apply button is clicked.
//
// Note:       Autogenerated by xml2window.
//
// Programmer: xml2window
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void
QvisGraviTPlotWindow::apply()
{
    Apply(true);
}


// ****************************************************************************
// Method: QvisGraviTPlotWindow::makeDefault
//
// Purpose: 
//   Qt slot function called when "Make default" button is clicked.
//
// Note:       Autogenerated by xml2window.
//
// Programmer: xml2window
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void
QvisGraviTPlotWindow::makeDefault()
{
    GetCurrentValues(-1);
    atts->Notify();
    GetViewerMethods()->SetDefaultPlotOptions(plotType);
}


// ****************************************************************************
// Method: QvisGraviTPlotWindow::reset
//
// Purpose: 
//   Qt slot function called when reset button is clicked.
//
// Note:       Autogenerated by xml2window.
//
// Programmer: xml2window
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void
QvisGraviTPlotWindow::reset()
{
    GetViewerMethods()->ResetPlotOptions(plotType);
}


void
QvisGraviTPlotWindow::DiffColorChanged(const QColor &color)
{
    ColorAttribute temp(color.red(), color.green(), color.blue());
    atts->SetDiffColor(temp);
    SetUpdate(false);
    Apply();
}


void
QvisGraviTPlotWindow::SpecColorChanged(const QColor &color)
{
    ColorAttribute temp(color.red(), color.green(), color.blue());
    atts->SetSpecColor(temp);
    SetUpdate(false);
    Apply();
}


void
QvisGraviTPlotWindow::MaxReflectionsProcessText()
{
    GetCurrentValues(GraviTAttributes::ID_MaxReflections);
    Apply();
}


void
QvisGraviTPlotWindow::MaterialChanged(int val)
{
    if(val != atts->GetMaterial())
    {
        atts->SetMaterial(GraviTAttributes::MaterialType(val));
        SetUpdate(false);
        Apply();
    }
}


void
QvisGraviTPlotWindow::ScheduleTypeChanged(int val)
{
    if(val != atts->GetScheduleType())
    {
        atts->SetScheduleType(GraviTAttributes::Scheduler(val));
        SetUpdate(false);
        Apply();
    }
}


void
QvisGraviTPlotWindow::SamplesProcessText()
{
    GetCurrentValues(GraviTAttributes::ID_Samples);
    Apply();
}


void
QvisGraviTPlotWindow::JitterSizeProcessText()
{
    GetCurrentValues(GraviTAttributes::ID_JitterSize);
    Apply();
}


